### ISSUE TITLE
cant compile with vala 0.16

### ISSUE THREAD

**Issue by helmuthdu** [Keruspe/GPaste#27]
got this output from terminal while trying to compile:
make[2]: Nada a ser feito para `all'.
  VALAC  bin_gpaste_settings_vala.stamp
src/gpaste-settings/gpaste-settings.vala:301.12-301.17: error: The symbol`GPaste' could not be found
    public GPaste.Settings settings {
           ^^^^^^
src/gpaste-settings/gpaste-settings.vala:301.12-301.17: error: The symbol `GPaste' could not be found
    public GPaste.Settings settings {
           ^^^^^^
src/gpaste-settings/gpaste-settings.vala:301.12-301.17: error: The symbol`GPaste' could not be found
    public GPaste.Settings settings {
           ^^^^^^
src/gpaste-settings/gpaste-settings.vala:301.12-301.17: error: The symbol `GPaste' could not be found
    public GPaste.Settings settings {
           ^^^^^^
Compilation failed: 4 error(s), 0 warning(s)
